adams = Playwright.create(name: "Johanna Adams", email: "jadams@me.com", bio: "Johnna is a 2012 graduate of the Rita & Burton Goldburg MFA Program at Hunter College (led by Tine Howe), the 2011 recipient of the Princess Grace Award and a finalist for the 2012 Susan Smith Blackburn Award. Her play GIDION’S KNOT was published in the December 2012 issue of TCG’s American Theatre Magazine and received an ATCA/Steinberg Citation. She is a past Reva Shiner Award winner, winner of the OC Weekly’s Best Original Play award (twice), finalist for the Christopher Brian Wolk Award, finalist for the William Saroyan Prize and a New York Innovative Theatre Award nominee. Her play SANS MERCI was produced in New York by Flux Theatre Ensemble, and Boomerang Theatre produced her rhyming verse comedy, LICKSPITTLES, BUTTONHOLERS, AND DAMNED PERNICIOUS GO-BETWEENS. Johnna’s plays are published by Dramatists Play Service, Inc. and Original Works Publishing (www.originalworksonline.com).
www.johnnaadams.com", password: "adams")
harrower = Playwright.create(name: "David Harrower", email: "dharrower@me.com", bio: "Playwright David Harrower was born in Edinburgh in 1966. His first play, KNIVES IN HENS, was first produced in 1995 at the Traverse Theatre, Edinburgh. He is also the author of the plays KILL THE OLD TORTURE THEIR YOUNG (1998), and THE CHRYSALIDS (1999), adapted from John Wyndham's novel for the National Theatre's Connections project. PRESENCE (2001), his third original play, was first performed at the Royal Court Jerwood Theatre Upstairs in April 2001. David Harrower has also adapted versions of Pirandello's SIX CHARACTERS IN SEARCH OF AN AUTHOR (SIX CHARACTERS LOOKING FOR AN AUTHOR), first staged at the Young Vic in 2000; Chekhov's IVANOV (2002), performed at the National Theatre in autumn 2002; and Buchner's WOYZECK, performed at the Edinburgh Lyceum in 2002. He has also translated THE GIRL ON THE SOFA (2002), a play by Jon Fosse, presented in a joint production by the Edinburgh International Festival and the Schaubuhne, Berlin. His play DARK EARTH (2003) premiered at the Traverse in August 2003. He has also written a new version of Odon von Horvath's TALES FROM THE VIENNA WOODS (2003) for the National Theatre, London, which opened in October 2003. His play BLACKBIRD (2005) was commissioned by the Edinburgh International Festival, and he has also written an adaptation of Schiller's MARY STUART (2006). David Harrower lives in Glasgow.", password: "harrower")

#plays by adams
Play.create(name: "Sans Merci", genre: "Drama", synopsis: "Kelly, an idealistic young woman—and a survivor of rape and attempted murder by South American revolutionaries—is visited three years after the attack by the conservative mother of Tracy, the other victim. Slowly, the survivor and mother dance through their grief at losing Tracy, while negotiating the truth of what brought the two young women together, why they undertook their dangerous humanitarian mission, and what happened on that final day.", playwright_id: adams.id )
Play.create(name: "Gidion's Knot", genre: "Drama", synopsis: "Over the course of a parent/teacher conference, a grieving mother and an emotionally overwhelmed primary school teacher have a fraught conversation about the tragic suicide of the mother’s son, Gidion. Gidion may have been bullied severely—or he may have been an abuser. As his story is slowly uncovered, the women try to reconstruct a satisfying explanation for Gidion’s act and come to terms with excruciating feelings of culpability.", playwright_id: adams.id)
Play.create(name: "World Builders", genre: "Romantic Comedy", synopsis: "Max and Whitney both have personality disorders that cause them to retreat into imaginary worlds. When participating in a clinical drug trial that aims to rid them of their delusions, they fall in love. As the pills take effect and the fantasies subside, Max and Whitney must decide if romance is worth leaving their worlds behind.", playwright_id: adams.id)

#plays by harrower
Play.create(name: "Blackbird", genre: "Drama", synopsis: "This intense work was commissioned by the Edinburgh International Festival, where it received its world premiere. After years in prison and subsequent hardships, Ray, fifty-six, has a new identity and has made a new life for himself, thinking that he cannot be found. Una, twenty-seven, has thought of nothing else; upon seeing a photo of Ray in a magazine, she has arrived unannounced at his office. Guilt, rage, and raw emotions run high as they recollect the passionate relationship they had fifteen years ago, when she was twelve and he was forty. Without any moral judgments, the play never shies away from the brutal truth of this abandoned and unconventional love. Una is looking for answers, not vengeance. Nevertheless, the consequences are shattering.", playwright_id: harrower.id)
Play.create(name: "A Slow Air", genre: "Drama", synopsis: "Morna works as a cleaner for well-off families in Edinburgh. She spends her time drinking, attempting affairs and trying to understand her twenty-year-old son with whom she shares her Dalry flat. Athol, her elder brother by two years, lives near Glasgow airport with his wife, Evelyn. The owner of a floor-tiling company, with two grown-up children, Athol is proud of his hard-won achievements. Like any brother and sister they have fond and not-so-fond memories of their upbringing, differing views on their parents and definite opinions about each other. Especially so in their case, since Morna and Athol haven’t spoken to each other in fourteen years...When Morna’s son Joshua travels west to make contact with Athol he sets off, for all of them, a remarkable and life-changing series of events in this play from Olivier Award–winning playwright David Harrower.", playwright_id: harrower.id)
